Fix: `3d-force-graph` library error
The `3d-force-graph` library is throwing a TypeError because `onNodeDblClick` is not a function.  This commit aims to resolve this error.